### ISSUE TITLE
Update to React v16

### ISSUE THREAD

**Issue by amoghpalnitkar** [mobilusoss/react-notification-badge#31]
I am building on the latest react (v16), but the library fails on peer dependency.
peer dependency is react@^15.5.4.
Are we planning for react 16 upgrade?

**Comment by Alameli** [comment]
+1

**Comment by palavrov** [comment]
+1

Is it necessary to have that peer dependency at all?
Or at least use ">=15.5.4" ...

**Comment by georgeOsdDev** [comment]
Already done.
https://github.com/mobilusoss/react-notification-badge/commit/2b745a05db827e0e84a851068096276023caa85b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
